templates:
  - key: "student_food"  # This is the key that will be used to identify the template (use the same for the template folder)
    name: "Student Food Sticker"  # Title displayed in the UI
    description: "The label to use for student_food in the fridge and freezer"
    emoji: "❄️"
    settings:  # settings are optional data used by the sticker
      expiration: 6  # The expiration time in days
    allowed_roles:  # The roles that can use this template. (case insensitive) to authorize all roles use "@everyone"
      - student
    daily_role_limits:  # The number of stickers each role can print per day (default is 25)
      student: 5

  - key: "swimmer_food"
    name: "Swimmers Food Label"
    description: "The label to use for swimmer_food in the fridge and freezer"
    emoji: "❄️"
    settings:
      expiration: 2
    allowed_roles:
      - piscine
    daily_role_limits:
      piscine: 5

  - key: "logo_42"
    name: "Logo 42"
    description: "A big 42 logo"
    emoji: "4️⃣"
    allowed_roles:
      - student
      - piscine
      - BDE
      - tuteur
      - bocal
    daily_role_limits:
      student: 1
      piscine: 0
      BDE: 5
      tuteur: 2

  - key: "qr_code"
    name: "QR Code"
    description: "A Big custom QR code"
    emoji: "🔗"
    allowed_roles:
      - Bocal
    fields:
      - name: "QR Code URL"
        key: "qr_code"
        max_length: 100
        placeholder: "The URL that will be encoded in the QR code."

  - key: "test"
    name: "Test"
    description: "Your favourite colour is red"
    emoji: "🧪"
    allowed_roles:
      Student: 1
      Bocal: 1
    fields:  # Additional fields (maximum 5) that the template may need to ask the user for (can only be of type text)
      - key: "name"
        name: "Name or Title"
        max_length: 20
        placeholder: "max 20 characters"
      - key: "description"
        name: "Description or Text"
        max_length: 100
        placeholder: "max 100 characters"
      - key: "picture"
        name: "Picture URL"
        max_length: 100
        placeholder: "Use pasteboard.co to upload your images."
      - key: "qr_code"
        name: "QR Code URL"
        max_length: 100
        placeholder: "The URL that will be encoded in the QR code."


#roles that can print the same stickers as the bocal role
bocal_like_roles:
  - experience
  - ADM
  - intern
  - comité
  - padawans


unlimited_users: # List of users that can print unlimited stickers
  - id: 0000
    name: "Marco Belarbi"
    reason: "creator of the project"
    agreement: "I agree to use the printer responsibly and to purchase a refill when using it frequently."
  - id: 0000
    name: "Jerome Jaquemet"
    reason: "contributor in the development of the project"
    agreement: "I agree to use the printer responsibly and to purchase a refill when using it frequently."

unlimited_roles: # List of roles that can print unlimited stickers
  - name: "Bocal"
    reason: "Bocal members"
  - name: "Fragbox"
    reason: "Fragbox members"
  - name: "BDE"
    reason: "BDE members"
